// backend/services/pdfService.js
// Renders a contract (AI-generated HTML) into a PDF with the signature
// and audit trail embedded. pdfkit can't render HTML, so we convert the
// HTML into a simple block structure (headings + paragraphs) first.
const PDFDocument = require('pdfkit');

const decodeEntities = (s) =>
  s.replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>')
   .replace(/&quot;/g, '"').replace(/&#39;|&apos;/g, "'").replace(/&nbsp;/g, ' ');

// Convert contract HTML into [{ type: 'heading'|'text', text }]
const htmlToBlocks = (html) => {
  const blocks = [];
  // Treat section titles as headings, everything else as paragraphs
  const parts = html.split(/(<h[1-3][^>]*>[\s\S]*?<\/h[1-3]>)/gi);
  for (const part of parts) {
    const headingMatch = part.match(/<h[1-3][^>]*>([\s\S]*?)<\/h[1-3]>/i);
    if (headingMatch) {
      const text = decodeEntities(headingMatch[1].replace(/<[^>]*>/g, ' ')).replace(/\s+/g, ' ').trim();
      if (text) blocks.push({ type: 'heading', text });
    } else {
      // Split remaining content on block-level closers so paragraphs stay separate
      const paragraphs = part
        .split(/<\/(?:p|div|li|ul|ol|tr)>/gi)
        .map((p) => decodeEntities(p.replace(/<[^>]*>/g, ' ')).replace(/\s+/g, ' ').trim())
        .filter((p) => p.length > 0);
      for (const p of paragraphs) blocks.push({ type: 'text', text: p });
    }
  }
  return blocks;
};

// Stream a contract PDF into the HTTP response
const streamContractPdf = (contract, res) => {
  const doc = new PDFDocument({ size: 'A4', margins: { top: 60, bottom: 60, left: 60, right: 60 } });

  res.setHeader('Content-Type', 'application/pdf');
  const safeTitle = (contract.title || 'contract').replace(/[^a-z0-9 _-]/gi, '').slice(0, 60);
  res.setHeader('Content-Disposition', `attachment; filename="${safeTitle}.pdf"`);
  doc.pipe(res);

  // Header
  doc.font('Helvetica-Bold').fontSize(18).text(contract.title, { align: 'center' });
  doc.moveDown(0.3);
  doc.font('Helvetica').fontSize(9).fillColor('#666666')
    .text(`Created ${new Date(contract.createdAt).toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}  ·  Status: ${contract.status.toUpperCase()}`, { align: 'center' });
  doc.moveDown(1);
  doc.moveTo(60, doc.y).lineTo(535, doc.y).strokeColor('#dddddd').stroke();
  doc.moveDown(1);

  // Body
  doc.fillColor('#111111');
  for (const block of htmlToBlocks(contract.content || '')) {
    if (block.type === 'heading') {
      doc.moveDown(0.6);
      doc.font('Helvetica-Bold').fontSize(12).text(block.text);
      doc.moveDown(0.3);
    } else {
      doc.font('Helvetica').fontSize(10).text(block.text, { lineGap: 3, align: 'justify' });
      doc.moveDown(0.4);
    }
  }

  // Signature + audit trail
  if (contract.signature?.data) {
    doc.moveDown(1.5);
    doc.moveTo(60, doc.y).lineTo(535, doc.y).strokeColor('#dddddd').stroke();
    doc.moveDown(1);
    doc.font('Helvetica-Bold').fontSize(12).text('Client Signature');
    doc.moveDown(0.5);
    try {
      const base64 = contract.signature.data.split(',')[1] || contract.signature.data;
      doc.image(Buffer.from(base64, 'base64'), { fit: [220, 80] });
    } catch {
      doc.font('Helvetica-Oblique').fontSize(10).text('[signature image unavailable]');
    }
    doc.moveDown(0.5);
    doc.font('Helvetica').fontSize(9).fillColor('#444444');
    doc.text(`Signed by: ${contract.signature.signerName || 'Client'}`);
    if (contract.signature.signerEmail) doc.text(`Email: ${contract.signature.signerEmail}`);
    doc.text(`Signed at: ${new Date(contract.signature.signedAt).toLocaleString('en-IN')}`);
    doc.moveDown(0.8);
    doc.font('Helvetica-Bold').fontSize(10).fillColor('#111111').text('Cryptographic Audit Trail');
    doc.font('Helvetica').fontSize(8).fillColor('#444444');
    doc.text(`IP Address: ${contract.signature.ip || 'N/A'}`);
    doc.text(`Device: ${contract.signature.userAgent || 'N/A'}`);
    doc.text(`Content Hash (SHA-256): ${contract.signature.contentHash || 'N/A'}`);
  }

  // Footer
  doc.moveDown(2);
  doc.font('Helvetica').fontSize(8).fillColor('#999999')
    .text('Generated by AI ContractKit · Secure & Legally Binding', { align: 'center' });

  doc.end();
};

module.exports = { streamContractPdf };
